steps:
# Шаг 0: Сборка Docker-образа с явным указанием рабочей директории
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/alina-kross-manager', 
    '.' # Контекст сборки - текущая директория (которая будет 'AlinaKrossManager')
  ]
  dir: 'AlinaKrossManager' # <-- Ключевой параметр: устанавливает рабочую директорию
  id: Build

# Шаг 1: Пуш Docker-образа
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/alina-kross-manager']
  id: Push

images:
- 'gcr.io/$PROJECT_ID/alina-kross-manager'