steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
       '--no-cache',  # ← ДОБАВЬТЕ ЭТУ СТРОКУ
      '-t', 'gcr.io/$PROJECT_ID/alina-kross-manager',
      '.'
    ]
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/alina-kross-manager']
    id: Push

images:
  - 'gcr.io/$PROJECT_ID/alina-kross-manager'