steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'GITHUB_USER=$_GITHUB_USER',
      '--build-arg', 'GITHUB_TOKEN=$_GITHUB_TOKEN',
      '-t', 'gcr.io/$PROJECT_ID/alina-kross-manager',
      '.'
    ]
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/alina-kross-manager']
    id: Push

images:
  - 'gcr.io/$PROJECT_ID/alina-kross-manager'